### ISSUE TITLE
retrying setup.sh?

### ISSUE THREAD

**Issue by Pomax** [wagtail/vagrant-wagtail-develop#13]
Is there a way to make setup.sh "retry" its setup process?

For instance, right now if you tried running it but it broke when it discovered vagrant had an issue, you can fix that issue, but then trying setup.sh again yields `fatal: destination path 'bakerydemo' already exists and is not an empty directory.` and just removing that dir then flags wagtail, and removing that flags a dir inside libs, and it's basically a matter of "wipe entire dir, reclone, rerun setup" which seems a bit overkill.

**Comment by gasman** [comment]
It'd probably be easy enough to add an 'if not exists' check before each of the git clone lines, although presumably that'd slightly break the instruction "On platforms that can't run shell scripts, run the commands from setup.sh manually instead"...

**Comment by Pomax** [comment]
Good point. Can shell scripts do comments? If so, a little "ignore everything below if you're running the instructions manually" comment might work?

**Comment by zerolab** [comment]
@shurph one you could look at?

**Comment by gasman** [comment]
Completed in #19
