### ISSUE TITLE
Elasticsearch version mismatch

### ISSUE THREAD

**Issue by shurph** [wagtail/vagrant-wagtail-develop#17]
The provision script from this repos installs the elasticsearch with version `5.3.3`.
But somewhere in next steps the version `2.4.1` is forced.

I think it would be good to decide which version is preferable and use the same version in both places.
```
default: Requirement already satisfied: certifi>=2017.4.17 in ./.virtualenvs/bakerydemo/lib/python3.6/site-packages (from requests<3.0,>=2.11.1->wagtail<2.4,>=2.3->-r /vagrant/bakerydemo/requirements/base.txt (line 7)) (2018.10.15)
    default: Installing collected packages: elasticsearch, wagtail
    default:   Found existing installation: elasticsearch 5.5.3
    default:     Uninstalling elasticsearch-5.5.3:
    default:       Successfully uninstalled elasticsearch-5.5.3
    default:   Found existing installation: wagtail 2.4a0
    default:     Uninstalling wagtail-2.4a0:
    default:       Successfully uninstalled wagtail-2.4a0
    default: Successfully installed elasticsearch-2.4.1 wagtail-2.3
```

**Comment by shurph** [comment]
the `2.4.1` version is required there: https://github.com/wagtail/bakerydemo/blob/master/requirements/base.txt#L5

**Comment by zerolab** [comment]
Worth submitting a PR to bakery demo with `elasticsearch>=5.0.0,<6.0.0` as seen in https://docs.wagtail.io/en/v2.3/topics/search/backends.html?highlight=elasticsearch#elasticsearch-backend

**Comment by shurph** [comment]
Sure. I'll make PR to the bakery demo.

But...
Actually, is it necessary to install elasticsearch by "wget + dpgk" in this repository? Especially if elasticsearch is installing by the bakery demo?

**Comment by gasman** [comment]
@shurph Once bakerydemo is upgraded to use Elasticsearch 5, it'll be fine to remove those installation steps from vagrant-wagtail-develop. (I think they only differ because Elasticsearch 5 support was new and experimental at some time in the past, and it was appropriate to have it in the developer image but not the public demo project...)

**Comment by shurph** [comment]
@gasman, @zerolab, so, as I understand it's impossible to update elasticsearch version in bakery demo because bakery demo is forced to support AWS t2.micro and AWS t2.small which are provide only ES 2.3. Right?

**Comment by shurph** [comment]
@gasman, yep, it seems like a best solution. I've created PR for this: https://github.com/wagtail/bakerydemo/pull/225

**Comment by shurph** [comment]
@gasman anyway, we have some ES versions mismatch in the bakery demo (2.3 <> 2.4). Details are there: https://github.com/wagtail/bakerydemo/issues/223

**Comment by gasman** [comment]
Fixed in https://github.com/wagtail/bakerydemo/pull/225
