### ISSUE TITLE
getting "npm command not found" after running setup.sh

### ISSUE THREAD

**Issue by ababic** [wagtail/vagrant-wagtail-develop#22]
After following the instructions in the README, `npm` commands will not work after activating the environment with `vagrant ssh`.

I am just seeing the following output in Terminal:
```
[bakerydemo bakerydemo]$ cd ../wagtail/
[bakerydemo wagtail]$ npm run test
The program 'npm' is currently not installed. To run 'npm' please ask your administrator to install the package 'npm'
```

Looking at the output generated by `setup.sh`, I can see the following output relating to the node/npm steps:
```
default: Installing node.js tooling...
default: -su: npm: command not found
```

**Comment by zerolab** [comment]
Can you try with:

```sh
# Install node.js and npm
su - vagrant -c "curl -sL https://deb.nodesource.com/setup_8.x | bash -"
su - vagrant -c "apt-get install -y nodejs"
```

before https://github.com/wagtail/vagrant-wagtail-develop/blob/master/vagrant/provision.sh#L102

and re-provision your box?

**Comment by ababic** [comment]
Thanks @zerolab. Yes, doing this solved the problem.

**Comment by zerolab** [comment]
Thank you for confirming, @ababic. Opened #23 to get this in.

**Comment by gasman** [comment]
My best guess is that this was a temporary network failure at the point where provision.sh was meant to install node. If you're able to reproduce this, please include the full console output and we can investigate further.

**Comment by ababic** [comment]
Have rebuilt the box twice, and can no longer reproduce the issue.
